# Generated by Django 3.2.8 on 2021-10-30 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('Collegename', models.CharField(max_length=50)),
                ('Specialization', models.CharField(max_length=50)),
                ('Degreename', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('Internship', models.CharField(choices=[('FE', 'Front-end web developer'), ('BE', 'Back-end web developer')], max_length=50)),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Notes', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userstatus', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
